name: customerapp
description: "Nook & Corner App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: 3.6.1
  flutter: 3.27.3


dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_it: ^8.0.0
  dio: ^5.7.0
  get_storage: ^2.1.1
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.8
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1
  package_info_plus: ^8.0.3
  flutter_toggle_tab: ^1.4.1
  json_annotation: ^4.9.0
  auto_size_text: 3.0.0
  shimmer: 3.0.0
  zip_future: 1.1.0
  tuple: 2.0.2
  collection: 1.19.0
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  webview_flutter: ^4.10.0
  flutter_rating_bar: ^4.0.1
  crypto: ^3.0.6
  encrypt: ^5.0.3
  video_player: ^2.9.2
  chewie: ^1.8.5
  flutter_launcher_icons: ^0.14.1
  permission_handler: ^11.3.1
  otp_autofill: ^4.1.0
  flutter_typeahead: ^5.2.0
  app_settings: ^5.2.0
  workmanager: ^0.5.2

  # Firebase
  firebase_core: ^3.12.0
  #firebase_crashlytics: ^4.3.3
  firebase_messaging: ^15.1.5
  firebase_analytics: ^11.4.3
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.5.0
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  flutter_lints: ^5.0.0


flutter_launcher_icons:
    image_path_android: "assets/images/nook_corner.png"
    image_path_ios: "assets/images/nook_corner.png"
    android: true
    ios: true
    adaptive_icon_background: "assets/images/launcher_background.png"
    adaptive_icon_foreground: "assets/images/nook_corner_transparent.png"
    min_sdk_android: 21
    android_enable_round_icon: true
    android_round_icon: true



flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600


flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true